name: Validacao

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build C11
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Compilar
        run: make

      - name: Validar inicializacao
        run: printf '0\n' | ./build/banco
